### ISSUE TITLE
Documentation / interrupt

### ISSUE THREAD

**Issue by Cysign** [cano64/ArduinoSleep#2]
Hi, I wonder if I could interrupt a sdelay-time with an interrupt?
Is there any documentation for this libary?

I'd also like to know what parts of the chip are still active during sdelay...

Also I'd like to know if sdelay needs an external crystal. Any ideas?

**Comment by cano64** [comment]
During sdelay() MCU will enter power down mode. In this mode, the Oscillator is stopped, while the external interrupts, and the Watchdog continue operating. External Reset, a Watchdog Reset, a Brown-out Reset, an external level interrupt on INT0, or a pin change interrupt can wake up the MCU
sdelay() doesn't need an external crystal

**Comment by Cysign** [comment]
Thanks!
