### ISSUE TITLE
AttachInterrupt reset

### ISSUE THREAD

**Issue by Cysign** [cano64/ArduinoSleep#3]
Hi guys,

I really love the functionality of this lib, but when I use it in combination with attachInterrupt(1, myFunction, FALLING[or LOW]) if often resets my ArduinoUno.

In my case I use the lib to save energy while my µC waits for an task.

void loop()
{
if (activated == 0){sdelay(3000);}
if (activated == 1){ <<<my  code here>>> }
}

I'd like to wake up my Arduino by attachInterrupt(1, activator, LOW);

void activator () {acticated = 1;}

But that resets my Arduino. Is there a known issue using sdelay() in combination with RTC modules or PCF8574 on an HD44780 module?

Tha libs I'm using in this sketch are:
# include "sdelay.h"
# include <Wire.h>
# include <OneWire.h>
# include <DallasTemperature.h> // to read an DS1820
# include <LiquidCrystal_I2C.h> // HD44780 on PCF8574
# include <EEPROM.h>
# include <Time.h>
# include <DS1307RTC.h>

**Comment by cano64** [comment]
Hi, 
This library shouldn't cause reset with a use of waking up on interrupt.
Do you use watchdog timer in your sketch or other libraries to reset the arduino when the timer overflows?

**Comment by Cysign** [comment]
I don't use any lib to reset.
No idea why my libs were removed above.... here they are:

sdelay.h
Wire.h
OneWire.h
DallasTemperature.h
LiquidCrystal_I2C.h
EEPROMex.h (I've been using EEPROM before, when the issue appeared)
Time.h
DS1307RTC.h

**Comment by cano64** [comment]
Not sure that Time.h is. Could it reset because the battery voltage is too low? Do you have BOD enabled?

**Comment by Cysign** [comment]
I've been testeing on USB power... I didn't disable BOD. Should I really do that?

In case of battery power I'm using 5v from an LP2950, which has 3000µF electrolytic capacitors on the input stage (as there is another consumer as well which draws a lot of power, a DC-DC converter which ends up in an dc motor), and 1000µF on the 5V output stage (which is only for logic level - hughest consumer: HD44780 display...but it's stll less than 70mA while the LP2950 is able to draw more than 100mA).

On the 12V stage I couldn't see any large up- and downturns with my oscilloscope. As the 5V stage has it's own capacitors behind the LP2950 there shouldn't be any fluctuation (but I'm unable to check it on the osc at the moment).

**Comment by Cysign** [comment]
One issue was using sdelay() in combination with hardware PWM.

analogWrite(pin, 150);
sdelay(sometime);
analogWrite(pin, 0);

This WILL cause random resets or freezes!
Also your PWM signal will be your value + a short intervall full power!
I've been testing this with an DC motor...first it sounds like PWM throttled, then it becomes more quiet while in full power mode (PWM throttling causes more noise than full power operation).

But I still have an issue with random resets. I think I need to add a diode + an extra capacitor between power- and logig-stage, to avoid reverse current when my motor turns on. I might test this on monday and tell you if all trouble in gone than.

**Comment by cano64** [comment]
You can't use PWM with sdelay. When the processor is sleeping main timer is not running and the processor is not performing any instructions. If you enter sleep mode when PWM, then the pin will either stay high or low. It should not cause freezing or resets though.

**Comment by Cysign** [comment]
PWM wasn't freezing, using an oscilloscope I got some crazy output...had nothing to do with PWM. And it caused random freezing or reboots!

Now that I'm using delay during an PWM signal, everything works fine.
Using my oscilloscope I can see some clean PWM signal now.

But I still have to re-check AttachInterrupt now...
