### ISSUE TITLE
Compatible to AtMega2560

### ISSUE THREAD

**Issue by Cysign** [cano64/ArduinoSleep#4]
Hey guys, might the lib be compatible with AtMega2560? Or does it need big changes for it?

**Comment by cano64** [comment]
I'm not sure if it works on AtMega2560, but sleeping official arduino boards doesn't make much sense because there is too much other stuff on the board that consumes more energy. The library is intended for standalone AtMega and AtTiny chips

**Comment by Cysign** [comment]
A stock adruino board indeed needs way too much power. But as I created my own PCB with an AtMega 2560 running the Arduino bootloader, it makes sense ;)

As I've testet it I can tell you: This library works with AtMega 2560 :)
Maybe someone could add it on the compatibility list?
Thanks!
