### ISSUE TITLE
ArduinoIDE 1.8.0

### ISSUE THREAD

**Issue by Cysign** [cano64/ArduinoSleep#6]
Hi, using sdelay.h with ArduinoIDE 1.8.0 i get this error:

sdelay.h:8: error: redefinition of 'void __vector_12()'

 ISR(WDT_vect) { 

     ^

sketch\sdelay.h:8:5: note: 'void __vector_12()' previously defined here

 ISR(WDT_vect) { 

How might I solve this?

**Comment by Cysign** [comment]
Stupid me. Double-included sdelay.h...

**Comment by Cysign** [comment]
But the .cpp file was the main problem ;)

**Comment by cano64** [comment]
I refactored the library, try now
