### ISSUE TITLE
sdelay forces reboot

### ISSUE THREAD

**Issue by Cysign** [cano64/ArduinoSleep#8]
sdelay(); forces reboot, while delay(); displays an increasing number on my display.
Here's the code:

`#include <Wire.h> 
#include <OneWire.h>
#include <DallasTemperature.h>
#include <LiquidCrystal_I2C.h>
#include <EEPROMex.h>
#include <Time.h>
/*#include <DS1307RTC.h>*/
#include <SPI.h>
#include <SD.h>
#include <sdelay.h>

LiquidCrystal_I2C lcd(0x27,20,4);

void setup()
{
    lcd.begin();
    lcd.clear();
    lcd.display();
    lcd.clear();
    lcd.backlight();
}

void loop()
{
    for (int i=0; i<5000000; i++)
    {
        lcd.setCursor(1,1);
        lcd.print(i);
        sdelay(500);
    }
}`

**Comment by Cysign** [comment]
Just to make sure it's not one of the other libraries, it's still forcing reboot using:
#include <LiquidCrystal_I2C.h>
#include <sdelay.h>

LiquidCrystal_I2C lcd(0x27,20,4);

void setup()
{
    lcd.begin();
    lcd.clear();
    lcd.display();
    lcd.clear();
    lcd.backlight();
}

void loop()
{
    for (int i=0; i<5000000; i++)
    {
        lcd.display();
        lcd.backlight();
        lcd.setCursor(1,1);
        lcd.print(i);
        delay(500);
        
        lcd.noDisplay();
        lcd.noBacklight();
        sdelay(500);
    }
}





I'm using the library on an AtMega2560 using stk500boot_v2_mega2560.hex as ArduinoBootloader.

**Comment by Cysign** [comment]
I rechecked with an ArduinoMega board using the SerialCallResponse example of the ArduinoIDE.
I used an increasing integer
`#include <sdelay.h>

int firstSensor = 0;    // first analog sensor
int secondSensor = 0;   // second analog sensor
int thirdSensor = 0;    // digital sensor
int inByte = 0;         // incoming serial byte
int i = 0;

void setup() {
  // start serial port at 9600 bps:
  Serial.begin(9600);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }

  pinMode(2, INPUT);   // digital sensor is on digital pin 2
  establishContact();  // send a byte to establish contact until receiver responds
}

void loop() {
  // if we get a valid byte, read analog ins:
  if (Serial.available() > 0) {
    // get incoming byte:
    inByte = Serial.read();
    // read first analog input, divide by 4 to make the range 0-255:
    firstSensor = analogRead(A0) / 4;
    // delay 10ms to let the ADC recover:
    delay(10);
    // read second analog input, divide by 4 to make the range 0-255:
    secondSensor = analogRead(1) / 4;
    // read  switch, map it to 0 or 255L
    thirdSensor = map(digitalRead(2), 0, 1, 0, 255);
    // send sensor values:
    Serial.write(firstSensor);
    Serial.write(secondSensor);
    Serial.write(thirdSensor);
  }
}

void establishContact() {
  while (Serial.available() <= 0) {
    Serial.print(i);   // send a capital A
    i++;
    delay(300);
  }
}`

Using sdelay I always get a 0 and the LEDs of the Arduino Mega board signal rebooting the device.

Using delay I get an increasing number using the ArduinoIDE's desial monitor.

So I asume there's something terribly wring with the library - as one year ago it worked fine using an AtMega2560 board.

**Comment by cano64** [comment]
I don't have experience with AtMega2560, and I haven't tested the library on AtMega2560, so I can't help you with it. You shouldn't be using sleep while using serial communication unless you are sure no data is being transmitted. Another feature of the watch dog timer is, it will reset the board if configured that way. I wonder if that is the default behavior on AtMega2560

**Comment by Cysign** [comment]
Well, on my first test I was using an HD44780 connected by iic with an PCF8574 to get some output (without serial communication) and the same behavior (reset) ocured.

I've been using sdelay() onw year ago on an AtMega2560 using the Arduino bootloader successfully.
So there have to be changes either on the compiler or on the library that avoid using this lib anymore.

I'll see if I cen get the lib work on an Arduino Uno or Nano - maybe this will gain some more details.

**Comment by Cysign** [comment]
As I have a Arduino Mega2560 board here (besides my own PCB with AtMega2560), tell me if you need me to test anything for you ;)

**Comment by cano64** [comment]
fixed
